apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutputapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      # volumes:
      #   - name: shared-storage
      #     persistentVolumeClaim: 
      #       claimName: image-claim
      containers:
        - name: logoutputcontainer
          image: logoutput:2.1
          imagePullPolicy: IfNotPresent
          # volumeMounts:
          #   - name: shared-storage
          #     mountPath: /usr/src/app/data
        - name: loginputcontainer
          image: loginput:2.1
          imagePullPolicy: IfNotPresent
          # volumeMounts:
          #   - name: shared-storage
          #     mountPath: /usr/src/app/data
