apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      # volumes:
      #   - name: storage
      #     persistentVolumeClaim:
      #       claimName: image-claim
      containers:
        - name: todo-app-container
          image: todo-app:1.12
          imagePullPolicy: IfNotPresent
          # volumeMounts:
          #   - name: storage
          #     mountPath: /usr/src/app/images
        - name: todo-app-frontend
          image: todo-app-frontend:1.13
          imagePullPolicy: IfNotPresent
